capablevms/cheri-examples

- Makefile
- hello-cxx.cpp
- hello.c
- include/common.h
- mmap.c
- set_bounds.c
- setjmp.c
- stackscan.c
Allow for c++ code to be used in the examples, and switch to purecap mode for the sysroot.
Also, switch to the intrinsics in all the examples to the ones from the sysroot as their header file work with c++.
The reason for the switch is that on the CHERI slack it was mentioned that the purecap mode should be the default.
> Enable c++

- sentry.c
The main idea behind sentries is that they protect the function pointers from being modified, read to/from. This allows emulation of most sealed capability modes. This example shows some of the use cases of sentry capabilities that I could think of. This is kind of strange to understand because CHERI switched to using sentry capabilities everywhere.
> Add a sentry example.

- shared_objects/.gitignore
- shared_objects/Makefile
- shared_objects/include/lib1.h
- shared_objects/include/lib2.h
- shared_objects/lib1.c
- shared_objects/lib2.c
- shared_objects/main.c
This example is needed to present the implications of using shared libraries. How they can be used as a proxy for deciding what is
public and what is private by means of what is being exported and how does it integrate with the changes made on the linker (rtld) as needed by CHERI. 
This is what lead to deciding to split the lua VM into multiple shared objects. But this example also contains the idea for creating compartments purely from the program counter capability (PCC) and using it to protect data that should be private for a function.
> Add example showing the usage of .so files.

- CMakeLists.txt
- README.md
- riscv64-purecap.cmake
* Use CMake to build all the cheri examples
* Select architecture to compile for from command line 
* Set tool chain and SDK paths based on architecture
*Note* : currently only the risc-v implementation is done
> cmake build file with riscv toolchain file

- .buildbot.sh
- Makefile
- riscv64-purecap.cmake
- shared_objects/Makefile
Switched from using `riscv64-unknown-freebsd13-clang` to
`clang --config cheribsd-riscv64-purcap.cfg`. Now the only
linker that can be used is llvm's lld by doing `-fuse-ld=lld`.
Also included the new cmake build system in the build script.
> Integrate the new compilation process, and add the cmake build to the .buildbot.sh build script.

- bors.toml
I have renamed the name of the builder on the buildbot server as the names: cheri-build-script and cheribuild-script are very confusing.
You can see it here: http://bencher14.soft-dev.org:8010/
> Rename the builder used for status for bors.

- example_allocators/freelist_allocator/Makefile
- example_allocators/freelist_allocator/README.md
- example_allocators/freelist_allocator/binary_trees.c
- example_allocators/freelist_allocator/freelist_allocator.c
- example_allocators/freelist_allocator/freelist_allocator.h
final example allocator - a segregated freelist with three size classes.
Cell sizes are encoded using CHERI metadata (capability bounds info).
> Example segregated freelist allocator for CHERI

- .buildbot.sh
- Makefile.morello
- Makefile.riscv64
Add Morello support to Makefile
- default architecture is Morello
- ENV files to switch to riscv64
> Add Morello support to Makefile

- CMakeLists.txt
Since Debian 10 only has 3.13.0 this requirement is a bit annoying!
> We don't need CMake 3.15.0.

- employee/Makefile
- employee/employee.c
- employee/full_privileges.c
- employee/include/employee.h
- employee/read_only.c
- tests/run_tests.sh
Simple example to show how permissions work. A struct is made read-only by setting CHERI_PERM_LOAD.
> Employee example to show permissions in action

- Makefile.morello
- Makefile.riscv64
- employee/Makefile
- The user should not be confused by not having a `bin` dir;
- The build should not fail because a `bin` dir does not exist.
> Create `bin` dir in Makefile

- employee/Makefile
- employee/employee.c
- employee/read_only.c
Actual tests did not detect this issue because they only test the Exception, NOT where it is caused.
Trying to access more than a member of the read-only struct cause an "In-Address Security Exception" due to:
```
// $HOME/cheri/cheribsd/lib/libc/string/strlen.c:[144-157]
...
#else /* __CHERI_PURE_CAPABILITY__ */
size_t
strlen(const char *str)
{
const char *p;
p = str;
// HERE, line 153 accessing *p raises the Exception
while (*p != '\0')
p++;
return (p - str);
}
#endif /* __CHERI_PURE_CAPABILITY__ */
```
This draft PR asks for any pieces of advice or wants to be a mean to discuss the issue. Thanks!
> Reading from the read-only struct should not cause an In-address Security Exception

- allocate.c
- bounds-cxx.cpp
- bounds.c
- example_allocators/bump_allocator/bad_client.c
- example_allocators/bump_allocator/good_client.c
- function.c
- general_bounds.c
- include/common.h
- mmap.c
- seal.c
- setjmp.c
- shared_objects/include/find_sentries.h
- shared_objects/main.c
- shared_objects/unexported_function.c
- stackscan.c
- timsort/timsort.c
`inspect_pointer` should print basic information explaining the permissions in a human-readable way, e.g. Rxrw.
`inspect_pointer` should have a meaningful name, `pp_cap` as in "pretty-print capability".
> Modified and refactored "inspect_pointer"

- employee/Makefile
- employee/sealed.c
Opening this draft PR to discuss if this is how we want to convey the information to the user.
This is just the first part of the `employee sealed` example. I thought to put all the ways to seal/unseal/restore privileges together at first. However, I think that would be better to have three separate smaller programs. This is the first one: explicitly sealing and unsealing. I am not sure that this is what we want.
> Restore full privileges by explicitly sealing and unsealing

- .clang-format
- Makefile.riscv64
- employee/include/employee.h
- employee/sealed.c
- example_allocators/bitmap_allocator/bitmap_alloc.c
- example_allocators/bitmap_allocator/good_client.c
- example_allocators/bump_allocator/bad_client.c
- example_allocators/bump_allocator/good_client.c
- example_allocators/freelist_allocator/binary_trees.c
- example_allocators/freelist_allocator/freelist_allocator.c
- mmap.c
- sentry.c
- setjmp.c
- shared_objects/compartment_per_object.c
- shared_objects/include/find_sentries.h
- stackscan.c
- timsort/include/timsort_lib.h
- xor_pointers.c
+ Some files were not `clang-formatted` automatically by the Makefile;
+ `clang-format` did not allow space after cast.
> Fix some formatting issues

- build/Makefile.vars.morello-purecap
A quick typo I found while working on the other PR. A comment stating "riscv64" instead of "morello" in a morello Makefile. I had missed this in my review.
> Typo fix in Makefile.vars

- hybrid/Makefile.common
- hybrid/Makefile.morello-hybrid
- hybrid/basic_ddc.c
- hybrid/ddc_invalid.c
- hybrid/ddc_null.c
- hybrid/include/utils.h
- include/common.h
This PR shows some simple interactions with the DDC:
- basic_ddc.c: very basic compartment switching
- ddc_null.c: crash when writing NULL
- ddc_invalid.c: crash when writing an invalid capability
> Some simple interactions with the Default Data Capability register

- hybrid/ddc_compartment_switching/ddc_compartment_switching_sentry.c
Lift the `ddc_compartment_switching.c` example to wrap the switching function in a sentry.
> DDC Compartment Switch with Sentry

- include/instructions.h
This applies a `clang-format` to `include/instructions.h` file to ensure
no further errors on future PRs.
> Format `instructions.h`

- hybrid/compartment_examples/Makefile.morello-hybrid
- hybrid/compartment_examples/call_sentry/main.c
- hybrid/compartment_examples/call_sentry/shared.s
- hybrid/compartment_examples/restrict_pcc/main.c
- hybrid/compartment_examples/restrict_pcc/shared.s
(this is an improvement over #49)
These examples aim to do two things:
* restrict the program capability counter (`PCC`)
* call a function outside PCC bounds via a sealed capability entry
(sentry)
Example `restrict_pcc` shows that we successfully restrict the `PCC`,
and that calling a function outside the `PCC` bounds fails, with an
expected `In-address space security exception`.
Example `call_sentry` shows how to call a function outside of restricted
`PCC` bounds via a sentry, as well as one (not fully secure) choice of
how to transition between a compartment (i.e., restricted permissions)
and a state with full permissions.
> Compartment call sentry

- hybrid/compartment_examples/comp_setup/main.c
- hybrid/compartment_examples/comp_setup/main.h
- hybrid/compartment_examples/comp_setup/shared.S
This example builds on previous ones, particularly improving the
`switch_compartment` (`shared.s:17`) function. This is a step towards
inter-compartment transition without the need of a more-priveleged entity
controlling the switch (but needing to set everything up before control is
relinquished to a compartment).
Some specific improvements over previous examples:
- the compartment switching function now reads information from memory
rather than from the stack. This allows compartments to call this function
from a constrained environment, without leaking capabilities beyond a few
prepared ones;
- we showcase the use of the compartment ID (`CID_EL0`) register to control
which compartment we are switching into. This is more of an example, as it
would entail compartments are aware of the ID …
> Compartment switch via memory stored data

- hybrid/compartment_examples/inter_comp_call/main.c
- hybrid/compartment_examples/inter_comp_call/main.h
- hybrid/compartment_examples/inter_comp_call/shared.S
This example adds a second compartment, and shows a possible design to
achieve inter-compartment switching without (much) privilege escalation.
In this file, we setup compartment information within array `comps`
(`main.c:84`). This information will be used by the assembly function
`switch_compartment`. Further, we save a capability to
`switch_compartment()` in a register (`main.c:102`), to be able to call
it from a bounded-PCC context, as well as a capability defining the area
of memory with compartment information (`main.c:101`). These could be
added to the memory area of each created compartment for better
security, as well as sealed.
Our two compartments provide one entry point each, `comp_f_fn`
(`shared.S:93`), and `comp_g_fn` (`shared.S:109`). The design is that
compartment `f` will …
> Add example showing inter-compartment switch

- .buildbot.sh
- shared_objects/build/Makefile.shared_objects
- shared_objects/include/find_sentries.h
- shared_objects/include/static_function.h
- shared_objects/main.c
- shared_objects/pcc_bounds_check_main.c
- shared_objects/static_function.c
- shared_objects/static_variable.c
- tests/run_cheri_examples.py
- tests/run_tests.sh
Draft PR to enhance what we already have in the shared_objects example. If you like the idea, I'll add the other tests/more tests we have discussed. Basically, I do with assertions what I checked in `gdb`.
> Add utility function and assertions to verify PCC bounds in shared objects

- capability_sharing/cap-to-file/README.md
- capability_sharing/leak-capability/README.md
- capability_sharing/mmap-shared-vs-private/Makefile.morello-purecap
- capability_sharing/mmap-shared-vs-private/Makefile.riscv64-purecap
- capability_sharing/mmap-shared-vs-private/README.md
- capability_sharing/mmap-shared-vs-private/build/Makefile.mmap_shared_vs_private
- capability_sharing/mmap-shared-vs-private/include/util.h
- capability_sharing/mmap-shared-vs-private/private_anon_main.c
- capability_sharing/mmap-shared-vs-private/private_file_main.c
- capability_sharing/mmap-shared-vs-private/shared_anon_main.c
- capability_sharing/mmap-shared-vs-private/shared_file_main.c
- capability_sharing/mmap-shared-vs-private/util.c
- capability_sharing/read-cap-from-file/README.md
- tests/run_tests.sh
Add examples that write capabilities to `mmap`ed memory.
These examples demonstrate what happens when you write tagged pointer values to various types of memory mappings:
* Anonymous private mapping (OK)
* Anonymous shared mapping (OK)
* File-backed private mapping (OK)
* File-backed shared mapping (segfault)
> Add examples that write capabilities to `mmap`ed memory.

- capability_sharing/read-cap-from-pipe-with-sh/Makefile.morello-purecap
- capability_sharing/read-cap-from-pipe-with-sh/Makefile.riscv64-purecap
- capability_sharing/read-cap-from-pipe-with-sh/README.md
- capability_sharing/read-cap-from-pipe-with-sh/build/Makefile.read-cap-from-pipe-with-sh
- capability_sharing/read-cap-from-pipe-with-sh/read.c
- capability_sharing/read-cap-from-pipe-with-sh/run.sh
- capability_sharing/read-cap-from-pipe-with-sh/write.c
- capability_sharing/read-cap-from-pipe/Makefile.morello-purecap
- capability_sharing/read-cap-from-pipe/Makefile.riscv64-purecap
- capability_sharing/read-cap-from-pipe/README.md
- capability_sharing/read-cap-from-pipe/build/Makefile.read-cap-from-pipe
- capability_sharing/read-cap-from-pipe/main.c
- tests/run_tests.sh
Interestingly enough, I can't reproduce the issue highlighted in my [previous PR](https://github.com/capablevms/cheri-examples/pull/70) using Unix pipes for IPC.
This PR contains 2 examples, both of which seem to work correctly (as in, any capabilities read from a pipe are going to be invalid).
The first example consists of two sibling processes connected to a pipe:
* a writer process that writes a capability to the write end of the pipe, and
* a reader process that reads the capability written by the writer process to the pipe. The reader reads an invalid capability
The second example is similar, except it relies on the shell to connect the two processes to a pipe.
> A couple of examples which fail to leak capabilities using pipes.

- capability_sharing/cap-to-file/README.md
- capability_sharing/cap-to-file/build/Makefile.cap-to-file
- capability_sharing/leak-capability/README.md
- capability_sharing/leak-capability/build/Makefile.leak-capability
- capability_sharing/mmap-shared-vs-private/README.md
- capability_sharing/mmap-shared-vs-private/build/Makefile.mmap_shared_vs_private
- capability_sharing/read-cap-from-file/README.md
- capability_sharing/read-cap-from-file/build/Makefile.read-cap-from-file
- capability_sharing/read-cap-from-pipe-with-sh/README.md
- capability_sharing/read-cap-from-pipe/README.md
- employee/README.md
- shared_objects/README.md
- syscall-restrict/README.md
- timsort/README.md
This fixes the copyright year (which I got wrong for some of my examples), as well as some README typos.
> Fix README typos and copyright year.

- hybrid/compartment_examples/comp_setup/include/base.h
- hybrid/compartment_examples/comp_setup/main.c
- hybrid/compartment_examples/comp_setup/shared.S
The `comp_setup` example doesn't build on `master`:
```
gabi@bencher14 ~/c/h/c/comp_setup > SSHPORT=10085 make -f ../Makefile.morello-hybrid run-main
/home/gabi/cheri/output/morello-sdk/bin/clang -E  shared.S > shared.s
shared.S:4:10: fatal error: 'main.h' file not found
^~~~~~~~
1 error generated.
make: *** [<builtin>: shared.s] Error 1
rm shared.s
```
It looks like `main.h` was accidentally removed at some point (#57). This patch reinstates it as `base.h` (for consistency with the other examples).
> Add the missing `base.h` file.

- README.md
Fixes https://github.com/capablevms/cheri-examples/issues/86.
> Clarify that GNU make is needed.

- cap_build.c
- tests/run_tests.sh
`cheri_cap_build` and `cheri_address_set` are similar, but not quite the same. We were previously unsure of what the difference between the two was; this example uses both and explains the differences between the two.
It's pretty explicit about what's going on and prints detailled messages describing the capabilities it constructs & prints. I figured it'd be useful to have some detail in there so we didn't have to re-parse the code every time we wanted to remember what the difference between the functions is.
Put together mostly by @0152la; I just cut down the program we were using as a scratchpad when figuring this out and tidied it into an example.
> Example comparing`cheri_cap_build` & `cheri_address_set`

- .buildbot.sh
- hybrid/cap_build.c
- tests/run_tests.sh
Unfortunately, when we moved calling the underlying CHERI instance via `script` (in #93), we omitted to ensure that the return code for the underlying tests was properly returned to the testing script it's being called from. This means we had some underlying silent failures in our CI. We attempt to fix them here, and to ensure future CI checks fail appropriately.
> Fix CI not failing

- build/Makefile.vars.morello-hybrid
- hybrid/threads_ddc.c
- tests/run_tests.sh
Check whether we can set DDCs for spawned threads individually, and independent from the main program thread.
> Add a hybrid example related to threads

- general_bounds.c
- hybrid/compartment_examples/inter_comp_call/base/main.c
- hybrid/compartment_examples/inter_comp_call/malicious_compartments/secure-redirect_clr/main.c
- hybrid/compartment_examples/inter_comp_call/malicious_compartments/secure-try_deref/main.c
- hybrid/compartment_examples/inter_comp_call/malicious_compartments/secure-update_ddc/main.c
- hybrid/compartment_examples/inter_comp_call/malicious_compartments/secure/main.c
Presumably due to internal CHERI changes, some of our tests were failing CI. They are now updated and fixed.
> Fix some failing tests
